### ISSUE TITLE
Stylegan Pytorch Ada pkl conversion

### ISSUE THREAD

**Issue by axel578** [nolan-dev/GANInterface#17]
Hello,

I am getting an error while trying to convert a stylegan pytorch ada model (.pkl) to a pb using your instructions, I get this error:
`Loading networks from "../file.pkl"...
Traceback (most recent call last):
  File "run_conversion.py", line 70, in <module>
    main()
  File "run_conversion.py", line 65, in main
    save_weights(args.network)
  File "run_conversion.py", line 24, in save_weights
    _G, _D, Gs = pretrained_networks.load_networks(network_pkl)
  File "/tmp/work/stylegan2/pretrained_networks.py", line 76, in load_networks
    G, D, Gs = pickle.load(stream, encoding='latin1')
ModuleNotFoundError: No module named 'torch_utils'`
Is there any way to solve this ?

**Comment by axel578** [comment]
Any knews ?

**Comment by nolan-dev** [comment]
Hey sorry for the late reply, I missed this question and haven't done much with this project lately.  Unfortunately there's a good chance modifications of the original stylegan2 won't work with the conversion script.  However, it may be worth adding torch-utils to https://github.com/nolan-dev/GANInterface/blob/master/pkl_conversion/requirements.txt and trying again.
